package com.ducthong.TopCV.extract_data.constant;

public class ExtractDataConstant {
    public static final String API_URL = "https://openrouter.ai/api/v1/chat/completions";
    public static final String API_KEY = "Bearer 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";
    public static final String MODEL = "deepseek/deepseek-prover-v2:free";
//    public static final String EXTRACT_INSTRUCTION = "{\n"
//            + "  \"fullName\": \"\",\n"
//            + "  \"email\": \"\",\n"
//            + "  \"dateOfBirth\": \"\",\n"
//            + "  \"phone\": \"\",\n"
//            + "  \"address\": \"\",\n"
//            + "  \"positionApply\": \"\",\n"
//            + "  \"award\": [\n"
//            + "    {\n"
//            + "      \"time\": \"\",\n"
//            + "      \"name\": \"\"\n"
//            + "    }\n"
//            + "  ],\n"
//            + "  \"education\": [\n"
//            + "    {\n"
//            + "      \"school\": \"\",\n"
//            + "      \"time\": \"\",\n"
//            + "      \"industry\": \"\",\n"
//            + "      \"description\": \"\"\n"
//            + "    }\n"
//            + "  ],\n"
//            + "  \"experience\": [\n"
//            + "    {\n"
//            + "      \"company\": \"\",\n"
//            + "      \"time\": \"\",\n"
//            + "      \"position\": \"\",\n"
//            + "      \"description\": \"\"\n"
//            + "    }\n"
//            + "  ],\n"
//            + "  \"technicalSkills\": [],\n"
//            + "  \"softSkills\": []\n"
//            + "}\n"
//            + "Give the extracted information in json format only (Fields without data will be left as null)";
        public static final String EXTRACT_INSTRUCTION = "{\n"
            + "  \"fullName\": \"\",\n"
            + "  \"email\": \"\",\n"
            + "  \"dateOfBirth\": \"\", string with format dd/MM/yyyy\n"
            + "  \"phone\": \"\",\n"
            + "  \"address\": \"\",\n"
            + "  \"positionApply\": \"\",\n"
            + "  \"award\": [\n"
            + "    {\n"
            + "      \"time\": \"\",\n"
            + "      \"name\": \"\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"education\": [\n"
            + "    {\n"
            + "      \"school\": \"\",\n"
            + "      \"time\": \"\",\n"
            + "      \"industry\": \"\",\n"
            + "      \"description\": \"\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"experience\": [\n"
            + "    {\n"
            + "      \"company\": \"\",\n"
            + "      \"time\": \"\",\n"
            + "      \"position\": \"\",\n"
            + "      \"description\": \"\"\n"
            + "    }\n"
            + "  ],\n"
            + "  \"technicalSkills\": [], // array of string\n"
            + "  \"softSkills\": [] // array of string\n"
            + "}\n"
            + "Provide only extracted information in json format (Fields without data will be left as null). Strictly follow the structure and fields in the above json string.";
}
